### ISSUE TITLE
Lab session feedback collection for milestone3

### ISSUE THREAD

**Issue by jackyho112** [UBC-MDS/DSCI532_Group210_JobsAnalysis#33]
Please leave your feedback here!

**Comment by jamesh4** [comment]
+ Graph 1 scaling could be changed so the earlier years with lower overall employees doesn't get obscured.
+ Is it not completely clear what the purpose of graph 1 is. Could suggest target audience, purpose, and potential insights from investigating the graphs. Communicate with the audience more.
+ Use a gradient for graph 2 since the categories can be ordered
+ The balanced option for graph 3 is a ambiguous, could be clarified a bit.
+ Bug with graph 3 balanced only showing under 50%.
+ Maybe a bit too much text
+ Graph 1 should be able to select multiple or all careers, indicate ability to search.

**Comment by jackyho112** [comment]
https://github.com/UBC-MDS/DSCI532_Group210_JobsAnalysis/issues/36
